---
title: "ST558 Project 2: Creating predictive models and automating Markdown reports."
author: "Josh Baber & Lan Lin"
date: '2022-07-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'F:\\Graduate\\NCSU_courses\\ST558\\projects\\Project_2\\OnlineNewsPopularity')
```

```{r, include=FALSE}
library(tidyverse)
library(reader)
library(corrplot)
```


Read in the data set
```{r}
# Read in the data set and remove the non-predictive variables 
shares_Data <- read_csv("OnlineNewsPopularity.csv")[-2:-1]
head(shares_Data)
```

Convert the dummy variables of channels to single categorical variable
```{r}
# create a single variable representing the data channel
channel <- factor(cbind(VALUE = factor(max.col(shares_Data[12:17]), ordered = TRUE)))
levels(channel) <- c( 'Lifestyle', 'Entertainment', 'Business', 'Social Media', 'Tech', 'World')

# Create a new data set using the single variable representing the data channel
shares_Data_chl <- shares_Data %>% select(-starts_with("data_channel")) %>% 
                     mutate(channel) %>% 
                     select(channel, everything())
```

Subset the data to work on the "Lifestyle" data channel 
```{r}
shares_Lifestyle <- shares_Data_chl %>% filter(channel == "Lifestyle")
```

```{r}
Correlation <- cor(shares_Lifestyle[-1], method = "spearman")

corrplot(Correlation, type = "upper", tl.pos = "lt")
corrplot(Correlation, type = "lower", method = "number", add = TRUE, diag = FALSE, tl.pos = "n")
```

